grocery_app/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from grocery_app.models import GroceryStore, GroceryItem, User
from flask_login import login_user, logout_user, login_required, current_user
from grocery_app import bcrypt

# Import app and db from events_app package so that we can run app
from grocery_app import app, db
from grocery_app.forms import GroceryStoreForm, GroceryItemForm, SignUpForm, LoginForm

main = Blueprint("main", __name__)
auth = Blueprint("auth", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/')
def homepage():
    all_stores = GroceryStore.query.all()
    print(all_stores)
    return render_template('home.html', all_stores=all_stores)

@main.route('/new_store', methods=['GET', 'POST'])
def new_store():
    # Creating new GroceryStore
    form = GroceryStoreForm()

    if form.validate_on_submit(): 
        new_GroceryStore = GroceryStore(
            title=form.title.data,
            address=form.address.data,
            created_by_id = current_user.id
        )
        db.session.add(new_GroceryStore)
        db.session.commit()
        
        flash('New GroceryStore was created successfully.')
        return redirect(url_for('main.store_detail', store_id=new_GroceryStore.id))

    return render_template('new_store.html', form=form)

@main.route('/new_item', methods=['GET', 'POST'])
def new_item():
    # Creating new GroceryItem
    form = GroceryItemForm()

    if form.validate_on_submit(): 
        new_GroceryItem = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data,
            created_by_id = current_user.id
        )
        db.session.add(new_GroceryItem)
        db.session.commit()
        
        flash('New GroceryItem was created successfully.')
        return redirect(url_for('main.item_detail', item_id=new_GroceryItem.id))

    return render_template('new_item.html', form=form)

@main.route('/store/<store_id>', methods=['GET', 'POST'])
def store_detail(store_id):
    # Accessing GroceryStore
    store = GroceryStore.query.get(store_id)
    form = GroceryStoreForm(obj=store)

    if form.validate_on_submit(): 
        new_GroceryStore = GroceryStore(
            title=form.title.data,
            address=form.address.data
        )
        db.session.add(new_GroceryStore)
        db.session.commit()
        
        flash('New GroceryStore was created successfully.')
        return redirect(url_for('main.store_detail', store_id=new_GroceryStore.id))

    store = GroceryStore.query.get(store_id)
    return render_template('store_detail.html', store=store, form=form)

@main.route('/item/<item_id>', methods=['GET', 'POST'])
def item_detail(item_id):
    # Accessing GroceryItem
    item = GroceryItem.query.get(item_id)
    form = GroceryItemForm(obj=item)

    if form.validate_on_submit(): 
        new_GroceryItem = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data
        )
        db.session.add(new_GroceryItem)
        db.session.commit()
        
        flash('New GroceryItem was created successfully.')
        return redirect(url_for('main.item_detail', item_id=new_GroceryItem.id))

    item = GroceryItem.query.get(item_id)
    return render_template('item_detail.html', item=item, form=form)

@main.route('/add_to_shopping_list/<item_id>', methods=['POST'])
def add_to_shopping_list(item_id):
    item = GroceryItem.query.filter_by(id=item_id).one()
    user = User.query.filter_by(username=current_user.username).one()
    user.shopping_list_items.append(GroceryItem.query.filter_by(id=item_id).one())
    db.session.add(item)
    db.session.commit()
    
    return redirect(url_for('main.shopping_list'))

@main.route('/shopping_list')
@login_required
def shopping_list():
    item = GroceryItem.query.join(GroceryItem.user_items).filter_by(id=current_user.id).all()

    return render_template('shopping_list.html', items=item)

#########################
# Authentication Routes #
#########################

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    print('in signup')
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash('Account Created.')
        print('created')
        return redirect(url_for('auth.login'))
    print(form.errors)
    return render_template('signup.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page if next_page else url_for('main.homepage'))
    return render_template('login.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.homepage'))

grocery_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                    <a href="/new_store">New Store</a>
                    <a href="/new_item">New Item</a>

                    {% if current_user.is_authenticated %}
                    <a href="/logout">Log Out</a>
                    <a href="/shopping_list">Shopping List</a>
                    {% else %}
                    <a href="/signup">Sign Up</a>
                    <a href="login">Log In</a>
                    {% endif %}

                </div>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>The best place to track prices and find the hottest deals!</em></p>

<h2>All Stores</h2>

{% for store in all_stores %}
<div class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item - {{ item.name }}</h1>

<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>

<form method="POST" action="{{ url_for('main.add_to_shopping_list', item_id=item.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Add item to your shopping list!</legend>

        {{ form.submit }}
    </fieldset>
</form>



<h2>Edit Item</h2>

<form method="POST" action="/item/{{ item.id }}">
    <fieldset>
        <legend>Please enter your information:</legend>

        <!-- Uses the `form` object passed in from the route to render a form. -->
        {{ form.csrf_token }}
        {% for error in item.name.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.name.label }}
        {{ form.name }}

        {% for error in form.price.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.price.label }}
        {{ form.price }}

        {% for error in form.category.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.category.label }}
        {{ form.category }}

        {% for error in form.photo_url.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.photo_url.label }}
        {{ form.photo_url }}

        {% for error in form.store.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.store.label }}
        {{ form.store }}

        {{ form.submit }}

    </fieldset>
</form>

{% endblock %}

grocery_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
    
        {% for error in form.username.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        
        {{ form.password.label }}
        {{ form.password }}
    
        {% for error in form.password.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST" action="/new_item">
    <fieldset>
        <legend>Please enter your information:</legend>
        {{ form.csrf_token }}
        <!-- Uses the `form` object passed in from the route to render a form. -->
        {% for error in form.name.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.name.label }}
        {{ form.name }}

        {% for error in form.price.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.price.label }}
        {{ form.price }}

        {% for error in form.category.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.category.label }}
        {{ form.category }}

        {% for error in form.photo_url.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.photo_url.label }}
        {{ form.photo_url }}

        {% for error in form.store.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.store.label }}
        {{ form.store }}

        {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form method="POST" action="/new_store">
    <fieldset>
        <legend>Please enter the store information:</legend>
        {{ form.csrf_token }}
        <!-- Uses the `form` object passed in from the route to render a form. -->
        {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.title.label }}
        {{ form.title }}

        {% for error in form.address.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.address.label }}
        {{ form.address }}

        {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

grocery_app/templates/shopping_list.html
{% extends 'base.html' %}
{% block content %}

<h1><p><strong>{{ current_user.username }}'s Shopping Cart</strong></p></h1>

<div class="items">
    {% for item in items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
        <p><strong>Store: {{ item.store }}</strong></p>
    </div>
    {% endfor %}
</div>

{% endblock %}

grocery_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
    
        {% for error in form.username.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        

        {{ form.password.label }}
        {{ form.password }}
    
        {% for error in form.password.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>

<strong>Address:</strong> {{ store.address }}

<h2>Items</h2>

<div class="items">
    {% for item in store.items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Store</h2>

<form method="POST" action="/store/{{store.id}}">
    <fieldset>
        <legend>Please enter your information:</legend>
        {{ form.csrf_token }}
        <!-- Uses the `form` object passed in form the route to render a form. -->
        {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.title.label }}
        {{ form.title }}

        {% for error in form.address.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.address.label }}
        {{ form.address }}

        {{ form.submit }}

    </fieldset>
</form>

{% endblock %}